### PR TITLE
Rounded Button on Landing Page

### PR DESCRIPTION
**Pull request by faizshahudin**
Amir, I already change all buttons in landing page to rounded. In addition to that, I also created a button component for a better component structure. Please check the code before merging them. Thank you

### CODE REVIEW

**Comment by amirabuhasan** [comment]
Bro, thanks for moving to a Button component. We can definitely improve the component structure once we finish all the tickets. Btw, the buttons are too round haha. Work with Eunice to see what she wants

**Comment by amirabuhasan** [comment]
Other than that should be ok

**Comment by amirabuhasan** [comment]
Ehh Opan, btw the rounded buttons are only for the landing pages - Home, Owners, and Parkers. Not the whole application

**Comment by faizshahudin** [comment]
@amirabuhasan , "Home, Owners, and Parkers" maksud ko button yg mane? Dkt top navigation ke?

**Pull request merged**
